export const vehicle = {
  consumption_wh_per_mile: 480,
  practical_miles_at_80_percent: 226,
};

export const constraints = {
  max_miles: 200,
  min_end_soc: 25,
  start_soc: 95,
};

export const locations = {
  hotel: {
    name: "SpringHill Suites Island Park Yellowstone",
    shortName: "Hotel",
    kind: "hotel",
    lat: 44.5001,
    lng: -111.337978,
    source: "Marriott address; mapped property coordinates",
  },
  westEntrance: {
    name: "Yellowstone West Entrance",
    shortName: "West Entrance",
    kind: "gate",
    lat: 44.658408,
    lng: -111.097186,
    source: "Yellowstone entrance GPS reference",
  },
  madisonJunction: {
    name: "Madison Junction",
    shortName: "Madison Junction",
    kind: "stop",
    lat: 44.6457,
    lng: -110.8579,
    source: "OpenStreetMap road junction",
  },
  grandPrismatic: {
    name: "Grand Prismatic Spring",
    shortName: "Grand Prismatic",
    kind: "stop",
    lat: 44.525026,
    lng: -110.838135,
    source: "USGS geographic feature coordinates",
  },
  oldFaithful: {
    name: "Old Faithful",
    shortName: "Old Faithful",
    kind: "stop",
    lat: 44.459626,
    lng: -110.831287,
    source: "OpenStreetMap Old Faithful area",
  },
  westThumb: {
    name: "West Thumb Geyser Basin",
    shortName: "West Thumb",
    kind: "stop",
    lat: 44.4166,
    lng: -110.5729,
    source: "OpenStreetMap visitor area",
  },
  lakeYellowstone: {
    name: "Lake Yellowstone Hotel",
    shortName: "Lake Yellowstone",
    kind: "stop",
    lat: 44.549964,
    lng: -110.400856,
    source: "OpenStreetMap Lake Yellowstone Hotel",
  },
  norris: {
    name: "Norris Geyser Basin",
    shortName: "Norris Geyser Basin",
    kind: "stop",
    lat: 44.728546,
    lng: -110.704375,
    source: "USGS geographic feature coordinates",
  },
  canyonVillage: {
    name: "Canyon Village",
    shortName: "Canyon Village",
    kind: "stop",
    lat: 44.734219,
    lng: -110.491904,
    source: "OpenStreetMap Canyon Village",
  },
  artistPoint: {
    name: "Artist Point",
    shortName: "Artist Point",
    kind: "stop",
    lat: 44.7214,
    lng: -110.4796,
    source: "OpenStreetMap viewpoint",
  },
  haydenValley: {
    name: "Hayden Valley",
    shortName: "Hayden Valley",
    kind: "wildlife",
    lat: 44.644,
    lng: -110.468,
    source: "OpenStreetMap road corridor",
  },
  mammoth: {
    name: "Mammoth Hot Springs",
    shortName: "Mammoth Hot Springs",
    kind: "stop",
    lat: 44.975556,
    lng: -110.703415,
    source: "OpenStreetMap Mammoth visitor area",
  },
  towerFall: {
    name: "Tower Fall",
    shortName: "Tower Fall",
    kind: "stop",
    lat: 44.9166,
    lng: -110.4206,
    source: "OpenStreetMap Tower Fall area",
  },
  lamarValley: {
    name: "Lamar Valley",
    shortName: "Lamar Valley",
    kind: "wildlife",
    lat: 44.859019,
    lng: -110.187967,
    source: "Mapped Lamar Valley road corridor",
  },
  westSupercharger: {
    name: "West Yellowstone Tesla Supercharger",
    shortName: "Tesla Supercharger",
    kind: "charger",
    lat: 44.65599,
    lng: -111.09901,
    connector: "NACS",
    power: "Up to 150 kW",
    source: "Tesla/OpenStreetMap",
  },
  oldFaithfulCharger: {
    name: "Old Faithful Lodge EV Chargers",
    shortName: "Old Faithful EV",
    kind: "charger",
    lat: 44.458518,
    lng: -110.823913,
    connector: "J1772",
    power: "Level 2, 7.7 kW",
    source: "NPS/OpenStreetMap",
  },
  canyonCharger: {
    name: "Canyon Village EV Chargers",
    shortName: "Canyon EV",
    kind: "charger",
    lat: 44.7347,
    lng: -110.4878,
    connector: "J1772",
    power: "Level 2, 7.7 kW",
    source: "NPS lodge location",
  },
  mammothCharger: {
    name: "Mammoth Hot Springs Hotel EV Chargers",
    shortName: "Mammoth EV",
    kind: "charger",
    lat: 44.9762,
    lng: -110.701,
    connector: "J1772",
    power: "Level 2, 7.7 kW",
    source: "NPS hotel location",
  },
  lakeCharger: {
    name: "Lake Village EV Chargers",
    shortName: "Lake Village EV",
    kind: "charger",
    lat: 44.5508,
    lng: -110.396,
    connector: "J1772",
    power: "Level 2, 7.7 kW",
    source: "NPS Lake Village location",
  },
};

export const chargerIds = [
  "westSupercharger",
  "oldFaithfulCharger",
  "canyonCharger",
  "mammothCharger",
  "lakeCharger",
];

export const itineraryDays = {
  day1: {
    shortLabel: "D1",
    label: "Day 1",
    color: "#d85a16",
    title: "Grand Prismatic and Old Faithful",
    copy: "Arrival-day route through Madison Junction, Grand Prismatic, and Old Faithful.",
    route: [
      "hotel",
      "westEntrance",
      "madisonJunction",
      "grandPrismatic",
      "oldFaithful",
      "westSupercharger",
      "hotel",
    ],
    gate: "westEntrance",
    chargeStop: "westSupercharger",
    chargeNote: "Optional top-up before hotel",
    chargeTargetSoc: 90,
  },
  day2: {
    shortLabel: "D2",
    label: "Day 2",
    color: "#1267c7",
    title: "Old Faithful and Yellowstone Lake",
    copy: "South loop through Old Faithful, West Thumb, and Lake Yellowstone.",
    route: [
      "hotel",
      "westEntrance",
      "madisonJunction",
      "oldFaithful",
      "westThumb",
      "lakeYellowstone",
      "hotel",
    ],
    gate: "westEntrance",
    chargeStop: null,
    chargeNote: "No planned charge",
  },
  day3: {
    shortLabel: "D3",
    label: "Day 3",
    color: "#25783f",
    title: "Canyon and Hayden Valley",
    copy: "Norris, Canyon Village, Artist Point, and Hayden Valley wildlife route.",
    route: [
      "hotel",
      "westEntrance",
      "madisonJunction",
      "norris",
      "canyonVillage",
      "artistPoint",
      "haydenValley",
      "hotel",
    ],
    gate: "westEntrance",
    chargeStop: null,
    chargeNote: "No planned charge",
  },
  day4: {
    shortLabel: "D4",
    label: "Day 4",
    color: "#6f2a9b",
    title: "Mammoth and Lamar Valley",
    copy: "Northern Yellowstone route through Mammoth, Tower Fall, and Lamar Valley.",
    route: [
      "hotel",
      "westEntrance",
      "madisonJunction",
      "norris",
      "mammoth",
      "towerFall",
      "lamarValley",
      "westSupercharger",
      "hotel",
    ],
    gate: "westEntrance",
    chargeStop: "westSupercharger",
    chargeNote: "Required before returning to hotel",
    chargeTargetSoc: 90,
    allowOver200: true,
  },
};

export const requiredMappedLocations = [
  "hotel",
  "westEntrance",
  "madisonJunction",
  "grandPrismatic",
  "oldFaithful",
  "canyonVillage",
  "norris",
  "mammoth",
  "lamarValley",
  "lakeYellowstone",
  "westSupercharger",
  ...chargerIds.slice(1),
];
