export const vehicle = {
  name: "2021 Tesla Model Y Long Range",
  consumption_wh_per_mile: 480,
  practical_miles_at_80_percent: 226,
  practical_miles_at_100_percent: 283,
};

export const constraints = {
  comfort_max_miles: 200,
  preferred_max_miles: 190,
  min_end_soc: 25,
  start_soc_range: "90-100%",
  primary_gate: "westEntrance",
};

export const locations = {
  hotel: {
    name: "SpringHill Suites Island Park Yellowstone",
    shortName: "Hotel",
    kind: "hotel",
    lat: 44.5001,
    lng: -111.337978,
  },
  westEntrance: {
    name: "Yellowstone West Entrance",
    shortName: "West Entrance",
    kind: "gate",
    lat: 44.658408,
    lng: -111.097186,
  },
  madisonRiver: {
    name: "Madison River",
    shortName: "Madison River",
    kind: "stop",
    lat: 44.647,
    lng: -110.977,
  },
  madisonJunction: {
    name: "Madison Junction",
    shortName: "Madison Junction",
    kind: "stop",
    lat: 44.645412,
    lng: -110.858423,
  },
  fireholeCanyon: {
    name: "Firehole Canyon Drive / Firehole Falls",
    shortName: "Firehole Canyon",
    kind: "stop",
    lat: 44.628812,
    lng: -110.863333,
  },
  grandPrismaticOverlook: {
    name: "Grand Prismatic Overlook Trailhead",
    shortName: "Grand Prismatic Overlook",
    kind: "must",
    lat: 44.5154,
    lng: -110.8328,
  },
  midwayGeyser: {
    name: "Midway Geyser Basin",
    shortName: "Midway Geyser Basin",
    kind: "must",
    lat: 44.528499,
    lng: -110.836032,
  },
  fireholeLake: {
    name: "Firehole Lake Drive",
    shortName: "Firehole Lake Drive",
    kind: "stop",
    lat: 44.54392,
    lng: -110.785295,
  },
  oldFaithful: {
    name: "Old Faithful",
    shortName: "Old Faithful",
    kind: "must",
    lat: 44.460464,
    lng: -110.828146,
  },
  upperGeyser: {
    name: "Upper Geyser Basin",
    shortName: "Upper Geyser Basin",
    kind: "must",
    lat: 44.462284,
    lng: -110.837414,
  },
  biscuitBasin: {
    name: "Biscuit Basin - closed",
    shortName: "Biscuit Basin closure",
    kind: "closed",
    lat: 44.485548,
    lng: -110.85501,
  },
  blackSand: {
    name: "Black Sand Basin",
    shortName: "Black Sand Basin",
    kind: "stop",
    lat: 44.462774,
    lng: -110.855134,
  },
  westThumb: {
    name: "West Thumb Geyser Basin",
    shortName: "West Thumb",
    kind: "must",
    lat: 44.417006,
    lng: -110.571968,
  },
  lakeVillage: {
    name: "Yellowstone Lake / Lake Village",
    shortName: "Yellowstone Lake",
    kind: "must",
    lat: 44.558007,
    lng: -110.397681,
  },
  fishingBridge: {
    name: "Fishing Bridge",
    shortName: "Fishing Bridge",
    kind: "stop",
    lat: 44.5666,
    lng: -110.382065,
  },
  haydenValley: {
    name: "Hayden Valley",
    shortName: "Hayden Valley",
    kind: "must",
    lat: 44.643619,
    lng: -110.45622,
  },
  norris: {
    name: "Norris Geyser Basin",
    shortName: "Norris Geyser Basin",
    kind: "stop",
    lat: 44.72655,
    lng: -110.702809,
  },
  canyonVillage: {
    name: "Canyon Village",
    shortName: "Canyon Village",
    kind: "stop",
    lat: 44.73557,
    lng: -110.490955,
  },
  artistPoint: {
    name: "Artist Point",
    shortName: "Artist Point",
    kind: "must",
    lat: 44.721267,
    lng: -110.479408,
  },
  upperFallsView: {
    name: "Upper Falls View",
    shortName: "Upper Falls View",
    kind: "stop",
    lat: 44.714644,
    lng: -110.497233,
  },
  lowerFallsView: {
    name: "Lower Falls View",
    shortName: "Lower Falls",
    kind: "must",
    lat: 44.718196,
    lng: -110.496307,
  },
  lookoutPoint: {
    name: "North Rim / Lookout Point",
    shortName: "Lookout Point",
    kind: "stop",
    lat: 44.720884,
    lng: -110.488581,
  },
  grandView: {
    name: "Grand View",
    shortName: "Grand View",
    kind: "stop",
    lat: 44.722632,
    lng: -110.484032,
  },
  mammoth: {
    name: "Mammoth Hot Springs",
    shortName: "Mammoth Hot Springs",
    kind: "must",
    lat: 44.97649,
    lng: -110.699632,
  },
  upperTerrace: {
    name: "Upper Terrace Drive",
    shortName: "Upper Terraces",
    kind: "stop",
    lat: 44.965814,
    lng: -110.711493,
  },
  lowerTerrace: {
    name: "Lower Terraces",
    shortName: "Lower Terraces",
    kind: "stop",
    lat: 44.97062,
    lng: -110.70564,
  },
  towerFall: {
    name: "Tower Fall",
    shortName: "Tower Fall",
    kind: "must",
    lat: 44.893832,
    lng: -110.387183,
  },
  westernLamar: {
    name: "Western Lamar Valley",
    shortName: "Western Lamar",
    kind: "must",
    lat: 44.934,
    lng: -110.355,
  },
  sloughCreek: {
    name: "Slough Creek turnaround",
    shortName: "Slough Creek",
    kind: "stop",
    lat: 44.943564,
    lng: -110.308193,
  },
  westSupercharger: {
    name: "West Yellowstone Tesla Supercharger",
    shortName: "West Yellowstone Supercharger",
    kind: "charger",
    lat: 44.65599,
    lng: -111.09901,
  },
  oldFaithfulCharger: {
    name: "Old Faithful Lodge Level 2",
    shortName: "Old Faithful L2",
    kind: "backup-charger",
    lat: 44.458518,
    lng: -110.823913,
  },
  canyonCharger: {
    name: "Canyon Village Level 2",
    shortName: "Canyon L2",
    kind: "backup-charger",
    lat: 44.7347,
    lng: -110.4878,
  },
  mammothCharger: {
    name: "Mammoth Hotel Level 2",
    shortName: "Mammoth L2",
    kind: "backup-charger",
    lat: 44.9762,
    lng: -110.701,
  },
  lakeCharger: {
    name: "Lake Village Level 2",
    shortName: "Lake Village L2",
    kind: "backup-charger",
    lat: 44.5508,
    lng: -110.396,
  },
  gibbonFalls: {
    name: "Gibbon Falls",
    shortName: "Gibbon Falls",
    kind: "optional",
    lat: 44.654019,
    lng: -110.770746,
  },
  virginiaCascades: {
    name: "Virginia Cascades",
    shortName: "Virginia Cascades",
    kind: "optional",
    lat: 44.713078,
    lng: -110.647758,
  },
  roaringMountain: {
    name: "Roaring Mountain",
    shortName: "Roaring Mountain",
    kind: "optional",
    lat: 44.781102,
    lng: -110.740741,
  },
  sheepeaterCliff: {
    name: "Sheepeater Cliff",
    shortName: "Sheepeater Cliff",
    kind: "optional",
    lat: 44.891358,
    lng: -110.72982,
  },
};

export const backupChargerIds = [
  "oldFaithfulCharger",
  "canyonCharger",
  "mammothCharger",
  "lakeCharger",
];

export const itineraryDays = {
  day1: {
    shortLabel: "Tue",
    label: "Tuesday arrival afternoon",
    date: "June 30",
    type: "Partial day",
    color: "#d85a16",
    title: "West Corridor Loop",
    purpose: "Easy arrival-day route. No Old Faithful and no long north/south loop.",
    departure: "3:45 PM",
    returnEstimate: "9:30-10:15 PM",
    targetMiles: "65-70 mi planning target",
    targetEndSoc: 68,
    targetEndSocLabel: "65-70%",
    driveTime: "2.5-3 hr",
    walking: "2.5-3.5 mi",
    stopDuration: "3-3.5 hr",
    photoWindow: "Grand Prismatic overlook, about 5:30-7:00 PM",
    wildlifeWindow: "Opportunistic bison or elk along the Madison corridor",
    parking: "Use signed pullouts only. Grand Prismatic/Fairy Falls parking can require waiting.",
    bathrooms: "Madison area and Midway Geyser Basin seasonal restrooms.",
    foodPlan: "Carry snacks; have dinner in West Yellowstone while Supercharging.",
    weather: {
      summary: "Cool arrival afternoon, about 15-17°C, falling near 8-10°C late.",
      times: ["3p", "4p", "5p", "6p", "8p", "10p"],
      temperatures: [14.8, 16, 16.6, 16.3, 13.4, 7.6],
      rainChance: "Around 7%",
      wear: "Light layer, fleece for late evening, rain shell, walking shoes.",
    },
    route: [
      "hotel",
      "westEntrance",
      "madisonRiver",
      "fireholeCanyon",
      "grandPrismaticOverlook",
      "midwayGeyser",
      "fireholeLake",
      "westSupercharger",
      "hotel",
    ],
    mapStops: [
      "hotel",
      "westEntrance",
      "madisonRiver",
      "fireholeCanyon",
      "grandPrismaticOverlook",
      "midwayGeyser",
      "fireholeLake",
      "westSupercharger",
    ],
    optionalStops: [],
    schedule: [
      ["3:45 PM", "Hotel departure", "After check-in and a quick reset."],
      ["4:20 PM", "West Entrance", "Allow extra gate time if arrivals are backed up."],
      ["4:45 PM", "Madison River", "10-15 min scenic pullout."],
      ["5:05 PM", "Firehole Canyon Drive", "20-30 min one-way scenic drive."],
      ["5:45 PM", "Grand Prismatic Overlook", "60-75 min hike and photo time."],
      ["7:00 PM", "Midway Geyser Basin", "35-45 min boardwalk."],
      ["7:50 PM", "Firehole Lake Drive", "25-35 min scenic loop if open."],
      ["9:00 PM", "Supercharger + dinner", "Charge to the next morning's target."],
      ["9:30-10:15 PM", "Hotel", "Return and sleep."],
    ],
  },
  day2: {
    shortLabel: "Wed",
    label: "Wednesday full day",
    date: "July 1",
    type: "Full day",
    color: "#1267c7",
    title: "South Loop: Geysers, Lake, Hayden",
    purpose: "The major geyser, lake, and Hayden wildlife day. Hayden is not repeated Thursday.",
    departure: "5:45 AM",
    returnEstimate: "7:30-8:30 PM",
    targetMiles: "175-185 mi",
    targetEndSoc: 33,
    targetEndSocLabel: "30-35%",
    driveTime: "5.5-6.5 hr",
    walking: "4-6 mi",
    stopDuration: "7-8 hr",
    photoWindow: "Old Faithful/Upper Geyser early; West Thumb and lake before afternoon glare",
    wildlifeWindow: "Hayden Valley late morning through afternoon",
    parking: "Old Faithful is easiest early. Use Hayden pullouts; never stop in a traffic lane. Allow up to 15 minutes at the Gibbon River Bridge in early July.",
    bathrooms: "Old Faithful, West Thumb, Lake Village, Fishing Bridge, and Canyon corridor.",
    foodPlan: "Packed breakfast; early lunch at Old Faithful or Lake; snacks for Hayden; dinner while charging.",
    weather: {
      summary: "Cold 3-4°C start, warming to about 22°C; small afternoon shower chance.",
      times: ["6a", "9a", "12p", "3p", "6p", "9p"],
      temperatures: [3.4, 13.2, 19.1, 21.5, 21.5, 10.3],
      rainChance: "Up to 22%",
      wear: "Warm dawn layers, breathable midday shirt, sun hat, rain shell.",
    },
    route: [
      "hotel",
      "westEntrance",
      "madisonJunction",
      "oldFaithful",
      "upperGeyser",
      "biscuitBasin",
      "blackSand",
      "westThumb",
      "lakeVillage",
      "fishingBridge",
      "haydenValley",
      "westSupercharger",
      "hotel",
    ],
    mapStops: [
      "hotel",
      "westEntrance",
      "madisonJunction",
      "oldFaithful",
      "upperGeyser",
      "biscuitBasin",
      "blackSand",
      "westThumb",
      "lakeVillage",
      "fishingBridge",
      "haydenValley",
      "westSupercharger",
    ],
    optionalStops: [],
    schedule: [
      ["5:45 AM", "Hotel departure", "Packed breakfast in the car."],
      ["6:20 AM", "West Entrance", "Continue directly toward Old Faithful."],
      ["7:15 AM", "Old Faithful", "75-90 min including eruption timing."],
      ["8:45 AM", "Upper Geyser Basin", "90-120 min boardwalk walk."],
      ["10:45 AM", "Biscuit Basin", "Closed: drive past only; do not enter."],
      ["11:00 AM", "Black Sand Basin", "30-40 min boardwalk."],
      ["12:10 PM", "West Thumb", "45-60 min lakeside boardwalk."],
      ["1:30 PM", "Lake Village", "45-60 min lunch and lakefront."],
      ["2:30 PM", "Fishing Bridge", "20-30 min visitor stop."],
      ["3:00-5:00 PM", "Hayden Valley", "Wildlife pullouts and patient viewing."],
      ["7:00 PM", "West Yellowstone Supercharger", "Evening charge and dinner."],
      ["7:30-8:30 PM", "Hotel", "Return for the night."],
    ],
  },
  day3: {
    shortLabel: "Thu",
    label: "Thursday full day",
    date: "July 2",
    type: "Full day",
    color: "#25783f",
    title: "Canyon and Waterfalls Loop",
    purpose: "Pure canyon day. No Lake Village and no repeat visit to Hayden Valley.",
    departure: "5:45 AM",
    returnEstimate: "6:30-7:30 PM",
    targetMiles: "145-160 mi",
    targetEndSoc: 38,
    targetEndSocLabel: "35-40%",
    driveTime: "4.5-5.5 hr",
    walking: "4-6 mi",
    stopDuration: "6-7 hr",
    photoWindow: "Artist Point around 9-10 AM; North Rim overlooks early afternoon",
    wildlifeWindow: "Incidental only; this is not a dedicated wildlife day",
    parking: "Artist Point fills quickly. Move between signed canyon lots rather than roadside parking.",
    bathrooms: "Norris parking area, Canyon Village, Artist Point, and North Rim facilities.",
    foodPlan: "Packed breakfast; lunch at Canyon Village; dinner in West Yellowstone while charging.",
    weather: {
      summary: "About 5°C at departure, warming to 22-23°C with low rain risk.",
      times: ["6a", "9a", "12p", "3p", "6p", "9p"],
      temperatures: [5.2, 15.3, 20.6, 22.5, 21.8, 12.7],
      rainChance: "Around 6%",
      wear: "Fleece at dawn, trail shoes for stairs, breathable layer, rain shell.",
    },
    route: [
      "hotel",
      "westEntrance",
      "norris",
      "canyonVillage",
      "artistPoint",
      "upperFallsView",
      "lowerFallsView",
      "lookoutPoint",
      "grandView",
      "westSupercharger",
      "hotel",
    ],
    mapStops: [
      "hotel",
      "westEntrance",
      "norris",
      "canyonVillage",
      "artistPoint",
      "upperFallsView",
      "lowerFallsView",
      "lookoutPoint",
      "grandView",
      "westSupercharger",
    ],
    optionalStops: ["gibbonFalls", "virginiaCascades"],
    schedule: [
      ["5:45 AM", "Hotel departure", "Drive directly to Norris."],
      ["6:50 AM", "Norris Geyser Basin", "75-90 min boardwalk."],
      ["8:45 AM", "Canyon Village", "Short bathroom/coffee reset."],
      ["9:15 AM", "Artist Point", "45-60 min major photo stop."],
      ["10:30 AM", "Upper Falls View", "25-35 min."],
      ["11:15 AM", "Lower Falls View", "45-60 min including stairs as comfortable."],
      ["12:30 PM", "Canyon lunch", "45-60 min."],
      ["1:45 PM", "North Rim / Lookout Point", "60-75 min."],
      ["3:00 PM", "Grand View", "25-35 min final overlook."],
      ["5:45 PM", "West Yellowstone Supercharger", "Charge and dinner."],
      ["6:30-7:30 PM", "Hotel", "Return for the night."],
    ],
  },
  day4: {
    shortLabel: "Fri",
    label: "Friday full day",
    date: "July 3",
    type: "Full day",
    color: "#6f2a9b",
    title: "North Loop: Mammoth, Tower, Western Lamar",
    purpose: "Western Lamar turnaround. Do not continue to Northeast Entrance unless Tesla navigation is comfortable.",
    departure: "4:45-5:00 AM",
    returnEstimate: "8:00-9:30 PM",
    targetMiles: "185-190 mi",
    targetEndSoc: 30,
    targetEndSocLabel: "Around 30%",
    driveTime: "6-7 hr",
    walking: "3-4.5 mi",
    stopDuration: "7-8 hr",
    photoWindow: "Mammoth terraces early morning; Lamar from about 9-11 AM",
    wildlifeWindow: "Western Lamar and Slough Creek, ideally before late morning",
    parking: "Mammoth early, Tower lots are limited, and Lamar viewing must use full pullouts. Allow up to 15 minutes at the Gardner River High Bridge.",
    bathrooms: "Mammoth, Tower/Roosevelt area, and seasonal Slough Creek facilities.",
    foodPlan: "Pack breakfast and lunch; use Mammoth/Roosevelt only if timing works; dinner while charging.",
    weather: {
      summary: "About 7°C at dawn, warming to 22-24°C; keep layers for exposed wildlife stops.",
      times: ["6a", "9a", "12p", "3p", "6p", "9p"],
      temperatures: [6.9, 13.1, 19.9, 22.3, 13.6, 14.7],
      rainChance: "Up to 22%",
      wear: "Warm dawn layer, breathable shirt, sun protection, rain shell, binoculars.",
    },
    route: [
      "hotel",
      "westEntrance",
      "norris",
      "mammoth",
      "towerFall",
      "westernLamar",
      "sloughCreek",
      "westSupercharger",
      "hotel",
    ],
    mapStops: [
      "hotel",
      "westEntrance",
      "norris",
      "mammoth",
      "upperTerrace",
      "lowerTerrace",
      "towerFall",
      "westernLamar",
      "sloughCreek",
      "westSupercharger",
    ],
    optionalStops: ["roaringMountain", "sheepeaterCliff"],
    schedule: [
      ["4:45-5:00 AM", "Hotel departure", "No later than 5:00 AM."],
      ["5:35 AM", "West Entrance", "Continue north without a long stop."],
      ["6:35 AM", "Norris", "Pass-through or 10-minute comfort stop."],
      ["7:20 AM", "Mammoth Hot Springs", "60-75 min terraces and breakfast."],
      ["8:35 AM", "Upper + Lower Terraces", "45-60 min."],
      ["9:45 AM", "Tower Fall", "30-40 min."],
      ["10:30 AM-12:30 PM", "Western Lamar", "Wildlife drive and pullouts."],
      ["12:30 PM", "Slough Creek turnaround", "Turn back here; no Northeast Entrance."],
      ["2:00 PM onward", "Return via Tower + Mammoth", "Optional stops only if battery and time permit."],
      ["7:15 PM", "West Yellowstone Supercharger", "Required evening charge and dinner."],
      ["8:00-9:30 PM", "Hotel", "Return for the night."],
    ],
  },
};

export const roadTripDays = [
  {
    label: "Day 0 / June 29",
    route: "Milpitas, CA -> Twin Falls, ID",
    start: "About 10:30 AM PT",
    overnight: "SureStay Hotel by Best Western Twin Falls",
    requiredChargers: ["Rocklin", "Sparks / Reno", "Winnemucca", "Elko", "Twin Falls"],
    optionalChargers: ["Colfax", "Fernley", "Battle Mountain"],
    food: [
      "Chat Bhavan - Rocklin",
      "Tandoori Flame - Reno / Sparks",
      "Himalayan Kitchen - Winnemucca",
      "India Bistro - Elko",
      "Swad Indian Cuisine - Battle Mountain",
      "Bombay Palace - Twin Falls",
    ],
  },
  {
    label: "Day 0 / June 30",
    route: "Twin Falls -> SpringHill Suites Island Park Yellowstone",
    start: "Leave after charging",
    overnight: "SpringHill Suites Island Park Yellowstone",
    requiredChargers: ["Twin Falls", "Pocatello", "Idaho Falls"],
    optionalChargers: ["Rexburg"],
    food: [
      "Little India - Pocatello",
      "India House - Idaho Falls",
      "Tandoori Oven - Idaho Falls",
      "Chutneys - Rexburg",
    ],
    arrival: "About 2:30-3:30 PM MT",
  },
];

export const driveHome = {
  label: "Saturday July 4",
  title: "Drive home to Milpitas",
  route: "Island Park -> Idaho Falls / Pocatello -> Twin Falls -> Nevada I-80 corridor -> Milpitas",
  departure: "Leave early",
  guidance: "No Yellowstone sightseeing by default. A very short Madison stop is optional only if departure remains early.",
  chargePlan: "Use Tesla live navigation for required stops; likely hubs include Idaho Falls/Pocatello, Twin Falls, Elko, Winnemucca, Sparks/Reno, and Rocklin.",
};

export const priorities = {
  must: [
    "Grand Prismatic Overlook",
    "Old Faithful",
    "Upper Geyser Basin",
    "West Thumb",
    "Yellowstone Lake",
    "Hayden Valley",
    "Artist Point",
    "Lower Falls",
    "Mammoth Hot Springs",
    "Lamar Valley",
  ],
  optional: [
    "Gibbon Falls",
    "Virginia Cascades",
    "Roaring Mountain",
    "Sheepeater Cliff",
    "Extra visitor centers",
  ],
  skip: [
    "Northeast Entrance",
    "Far Lamar beyond Slough Creek",
    "Long hikes",
    "Unnecessary midday hotel returns",
  ],
};
